### ISSUE TITLE
Problem with sendmail permissions on Ubuntu 22.04

### ISSUE THREAD

**Issue by sleighton** [desbma/sysstat_mail_report#8]
Ran into an issue with permissions on Ubuntu 22.04. As is, installing the package adds a sysstat-report@.service to systemd that has a section noted as #hardening

```
# hardening
DynamicUser=true
Group=mail
ReadOnlyPaths=/
ProtectHome=true
```

This causes the unit to run under a made up user with the group mail. Unfortunately on Ubuntu this user has no permissions to maildrop causing the script to fail and hang with hundreds of error messages

`postfix/postdrop[1511682]: warning: mail_queue_enter: create file maildrop/834894.1511682: Permission denied`

My solution was to comment out the above hardening section, reload the unit with sudo systemctl daemon-reload and things then started working since the unit runs as root configured that way.  Note that you have to killall postdrop to get rid of the hung postdrop's.

Hope this info helps someone running into this same issue on Ubuntu.

Love the reports!

Scott

**Comment by desbma** [comment]
If you only replace `ReadOnlyPaths=/` by `ProtectSystem=full`, does that work?

**Comment by sleighton** [comment]
Nope, same error. I also tried changing the group to postdrop but that just causes the user not to be able to execute the binary /usr/sbin/postdrop  since that apparently requires the mail group and I can only find a way to define one group in the systemd service.

It's running fine though with hardening section commented out.

Scott

**Comment by desbma** [comment]
I have added a comment in eab7e466f9e116eb9ba08ea1258590929b2120ef.

If you don't feel comfortable with leaving the service running unrestricted as root, you might want to try [shh](https://github.com/desbma/shh). It's a tool I created to generate hardening config for the service from runtime profiling on your system, so that would generate hardening options compatible with the specific permissions required by your postdrop setup.
